### ISSUE TITLE
Package causes the redo stack to be lost during Save

### ISSUE THREAD

**Issue by jeffhandley** [mattst/sublime-single-trailing-new-line#1]
**Repro steps:**
1. Type some code
2. Use Undo to undo typing that code
3. Save the file
4. Attempt to redo

**Expected:**
The code writing that was undone can be redone.

**Actual:**
The redo stack is empty

**Comment by jeffhandley** [comment]
I've found I could actually use this Sublime Text config setting to eliminate the need for this package though, which addresses my issue:

```
"ensure_newline_at_eof_on_save": true
```

**Comment by mattst** [comment]
I'm responding way too late but the _Single Trailing Newline_ plugin ensures **exactly one** trailing newline the _ensure_newline_at_eof_on_save_ ST setting ensures there is at least one newline but does not limit it to one as my plugin does (this is useful and even essential for some development systems).
